name: Publish Website to CPanel.

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build assets
        run: |
          npm install
          npm run build

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Or '8.2' OR Adjust based on your Laravel version
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader
        
      - name: Copy environment file # NB; Remember credentials accordingly.
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate application key
        run: php artisan key:generate

      - name: Clear cache
        run: |
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan route:clear
          php artisan optimize
          php artisan view:clear
          php artisan clear-compiled
      #     php artisan cache:clear

      - name: Update .env with DB credentials
        run: |
          sed -i "s/^DB_CONNECTION=.*/DB_CONNECTION=sample_db_con/" .env
          sed -i "s/^DB_HOST=.*/DB_HOST=${{ secrets.dbhost }}/" .env
          sed -i "s/^DB_PORT=.*/DB_PORT=${{ secrets.dbport }}/" .env
          sed -i "s/^DB_DATABASE=.*/DB_DATABASE=${{ secrets.dbdatabase }}/" .env
          sed -i "s/^DB_USERNAME=.*/DB_USERNAME=${{ secrets.dbusername }}/" .env
          sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.dbpassword }}/" .env
          echo "Database configuration environment variables set"

      # - name: Run database migrations
      #   run: php artisan migrate 

      - name: Debug FTP secrets.
        run: |
          echo "SERVER: ${{ secrets.SERVER }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"

      - name: Deploy to CPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.server}}
          username: ${{secrets.username}}
          password: ${{secrets.password}}
          server-dir: / # Adjust this if deploying to a subdirectory i.e.  /public_html/
          local-dir: ./ # Or ./public if only deploying built frontend
          dangerous-clean-slate: false

      - name: ✅ ✅ ✅ Congratulations!!! Deployment success ✅ ✅ ✅
        run: |
          echo "Deployment completed successfully!"